# https://github.com/pivotal/docs-platform-automation-reference-pipeline-config
resources:
- name: docs-platform-automation-reference-pipeline-config
  type: git
  source:
    branch: master
    uri: https://github.com/kerringtonwells/sample_bash_code_old.git

- name: minio-s3
  type: s3
  source:
    regexp: example-file-(.*).txt
    endpoint: http://concourse_minio1_1:9000 # work out how to configure this per-worker
    bucket: zipfilebucket
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    disable_ssl: true

- name: hello-world-docker-image
  type: docker-image
  source: { repository: praqma/network-multitool }

jobs:
- name: test-platform-automation
  plan:
  - aggregate:
    - get: docs-platform-automation-reference-pipeline-config
    - get: hello-world-docker-image
  - task: test-interpolate
    image: hello-world-docker-image
    file: docs-platform-automation-reference-pipeline-config/testconcourse.yml

- name: test-write-to-s3
  plan:
  - get: hello-world-docker-image
  - task: cat-example-file
    image: hello-world-docker-image
    config:
      platform: linux
      run:
        path: bash
        args:
        - -c
        - echo "This is an example file, created $(date)" > file-to-upload/example-file-1.txt
      outputs:
        - name: file-to-upload
  - put: minio-s3
    params:
      file: file-to-upload/example-file-*

- name: minio-s3-read-it-out
  plan:
  - aggregate:
    - get: hello-world-docker-image
    - get: minio-s3
  - task: get-s3-example
    image: hello-world-docker-image
    config:
      platform: linux
      inputs:
      - name: minio-s3
      run:
        path: bash
        args:
        - -c
        - cat minio-s3/example-file-*
